server:
  port: 4000
  env: release
  version: 1.0

mysql:
  host: 127.0.0.1
  port: 3306
  database: go_micro_toDoList
  username : root
  password: root
  charset: utf8mb4

etcd:
  address: 127.0.0.1:2379

redis:
  address: 127.0.0.1:6369
  password:
